import Head from 'next/head'
// import Image from 'next/image'
import { Inter } from '@next/font/google'
// import styles from '../styles/Home.module.css'
import RegisterForm from './register'
import Navbar from '../components/Navbar'
import { useState } from 'react'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  // const [regForm, setRegForm] = useState(false);
  // const [logForm, setLogForm] = useState(true);

  // const handleLogin = () => {
  //   setLogForm(true);
  //   setRegForm(false);
  // };

  // const handleRegister = () => {
  //   setLogForm(false);
  //   setRegForm(true);
  // };
  return (
    <>

      <Head>
        <title>Piton Technology</title>
        <meta name="description" content="Generated by Piton FS Team" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/piton.ico" />
      </Head>
      <Navbar />

      {/* <div className="flex justify-center gap-x-28 mt-2">
        <button
          onClick={handleLogin}
          className="bg-blue-500 w-28 hover:bg-blue-700 text-white font-medium py-2 px-6 rounded">
          Login
        </button>

        <button
          onClick={handleRegister}
          className="bg-blue-500 w-28 hover:bg-blue-700 text-white font-medium py-2 px-6 rounded">
          Register
        </button>
      </div>
      {logForm==true && regForm==false ? <LoginForm />:<RegisterForm/>} */}
      
    </>
  )
}
