import Head from 'next/head'
import { Inter } from '@next/font/google'
// import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar'
import { useRouter } from 'next/router'





const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const router = useRouter();

  const user =(typeof window !== "undefined") && localStorage.getItem("user") || "";

  if(user){
        return (
    <>
      <Head>
        <title>Piton Technology</title>
        <meta name="description" content="Generated by Piton FS Team" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/piton.ico" />
      </Head>
      <Navbar />
      
    </>
  )
  }else{
    if (typeof window === "undefined") return null;
    router.push("/login")
 
  }

  
}
